"""create fragrances table

Revision ID: 6191340581b7
Revises: 2aeae0dde8d4
Create Date: 2026-03-12 17:20:31.047284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6191340581b7'
down_revision: Union[str, Sequence[str], None] = '2aeae0dde8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragrances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('gender_category', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender_category IS NULL OR gender_category IN ('masculine', 'feminine', 'unisex')", name='ck_fragrances_gender_category_valid'),
    sa.CheckConstraint('release_year IS NULL OR release_year BETWEEN 1000 AND 2100', name='ck_fragrances_release_year_range'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name', name='uq_fragrances_brand_id_name')
    )
    op.create_index('ix_fragrances_brand_id', 'fragrances', ['brand_id'], unique=False)
    op.create_index('ix_fragrances_name', 'fragrances', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fragrances_name', table_name='fragrances')
    op.drop_index('ix_fragrances_brand_id', table_name='fragrances')
    op.drop_table('fragrances')
    # ### end Alembic commands ###
